# Generated by Django 5.0.6 on 2024-06-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sdacha_dz',
            name='assignment',
            field=models.TextField(),
        ),
    ]
